teams:
  - name: platform
    description: Platform engineers responsible for CI/CD and infrastructure
    privacy: closed
    roles:
      - username: jajera
        role: maintainer
  - name: devops
    description: DevOps team managing deployment pipelines and system reliability
    privacy: closed
    roles:
      - username: jajera
        role: maintainer
  - name: test
    description: Temporary team for testing permissions and automation
    privacy: closed
    roles:
      - username: jajera
        role: maintainer
