name: "🆕 New Team Request"
description: "Submit a request to create or update a GitHub team"
title: "[Team Request] <team-name>"
labels: ["team-request"]
body:
  - type: input
    id: team_name
    attributes:
      label: 🏷️ Team Name
      placeholder: platform-team
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      placeholder: "Team responsible for internal platform infrastructure"
    validations:
      required: false

  - type: input
    id: maintainers
    attributes:
      label: 👥 Maintainers (comma-separated)
      placeholder: alice, bob
    validations:
      required: false

  - type: input
    id: members
    attributes:
      label: 👤 Members (comma-separated)
      placeholder: carol, dave
    validations:
      required: false

  - type: dropdown
    id: privacy
    attributes:
      label: 🔒 Team Privacy
      options:
        - closed
        - secret
      default: 0
