repositories:
  - name: service-a
    description: "Service A Repository"
    private: true
    auto_init: true
    gitignore_template: Node
    license_template: mit
  - name: service-b
    description: "Service B Repository"
    private: true
    auto_init: true
