name: Create Repository from File
on:
  workflow_dispatch:
    inputs:
      config_file:
        description: 'Path to repository configuration file'
        required: true
        default: 'repos.yml'

jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Repository
        uses: actionsforge/actions-repo-ops@v1
        with:
          operation: create
          config_file: config/repos-config.yml
          github_token: ${{ secrets.GH_REPO_TOKEN }}
